function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 10-Nov-2019 11:19:54

% Create figure
figure1 = figure('InvertHardcopy','off','Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1,'LineWidth',3,'FontWeight','bold',...
    'FontSize',24,...
    'FontName','times new roman');
%% Uncomment the following line to preserve the X-limits of the axes
%  xlim(axes1,[200 2600]);
%% Uncomment the following line to preserve the Y-limits of the axes
%  ylim(axes1,[0 0.052]);
%% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[-1 1]);
box(axes1,'on');
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',3,'Parent',axes1);
set(plot1(1),'DisplayName','n=0','Color',[0 0 1]);
set(plot1(2),'DisplayName','n=1','Color',[1 0 0]);
set(plot1(3),'DisplayName','n=2','Color',[0 0 0]);
set(plot1(4),'DisplayName','n=3','Color',[0 1 0]);
set(plot1(5),'DisplayName','n=4','Color',[0 1 1]);
set(plot1(6),'DisplayName','n=5','Color',[1 1 0])

% Create xlabel
xlabel('t/t_A','FontWeight','bold','FontSize',24,...
    'FontName','times new roman');

% Create ylabel
ylabel('\gamma','FontWeight','bold','FontSize',24,...
    'FontName','times new roman');

% Create title
title({'(b) Hall-MHD'},'FontWeight','bold','FontSize',24,...
    'FontName','times new roman');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.823598711323067 0.359838656570614 0.0773809513165837 0.500403536963214]);

